-- ====================================================================
-- 🐾 Vibe Cat Care (전윤교의 고양이 돌봄 블로그) - Supabase DB 스키마 & RLS 정책
-- ====================================================================

-- 1. profiles: 회원 등급 관리 테이블
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL,
    role TEXT DEFAULT 'member' CHECK (role IN ('member', 'vip', 'admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. posts: 블로그 포스트 테이블 (돌봄일지, 사진첩, 팁)
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('log', 'photo', 'tip')),
    image_url TEXT,
    is_restricted BOOLEAN DEFAULT FALSE NOT NULL, -- 회원 전용 포스트 여부
    author_name TEXT DEFAULT '전윤교' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==========================================
-- 3. RLS (Row Level Security) 행 보안 정의
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- 3.1 profiles RLS 정책
CREATE POLICY "본인 프로필만 조회 가능" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

-- 3.2 posts RLS 정책 (권한 기반 콘텐츠 제어 핵심)
-- 1) 일반 공개 게시물 (is_restricted = false)은 누구나 조회 가능 (비회원 포함)
CREATE POLICY "공개 포스트는 누구나 읽기 가능" 
ON public.posts FOR SELECT 
USING (is_restricted = FALSE);

-- 2) 회원 전용 게시물 (is_restricted = true)은 로그인한 회원(role = 'vip' 또는 'admin' 또는 'member')만 조회 가능
CREATE POLICY "회원 전용 포스트는 인증 회원만 읽기 가능" 
ON public.posts FOR SELECT 
USING (
  auth.uid() IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE profiles.id = auth.uid() 
      AND profiles.role IN ('member', 'vip', 'admin')
  )
);

-- 3) 포스트 생성/수정/삭제는 관리자(admin) 권한을 가진 계정만 실행 가능
CREATE POLICY "관리자만 포스트 수정 가능" 
ON public.posts FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
  )
);

-- ==========================================
-- 4. 기초 테스트 데이터 삽입 (Seed Data)
-- ==========================================
INSERT INTO public.posts (title, excerpt, content, category, image_url, is_restricted)
VALUES 
('치즈냥이 ''보리''의 첫 방문 돌봄 일지', '겁이 많은 보리와 친해지기 위해 조심스럽게 다가갔던 첫 날의 기록입니다. 간식 하나로 마음을 열어준 보리...', '보리는 낯가림이 아주 심한 아이였습니다. 하지만 낮춰서 눈인사를 하고 차분히 기다리자 마음을 열어주고 츄르를 받아 먹었답니다. 감자 2개 캐고 모래 정리 완료했습니다.', 'log', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=800', true),
('외출 시 고양이 물그릇 배치 꿀팁', '고양이가 물을 더 많이 마시게 하는 효율적인 배치 장소와 신선도 유지 방법 5가지를 소개합니다.', '고양이는 흐르는 물과 넓은 그릇을 선호합니다. 밥그릇과 물그릇은 최소 1m 이상 떨어뜨려 놓아야 물의 신선함을 느낍니다.', 'tip', 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&q=80&w=800', false),
('오늘의 묘델: 우아한 샴 고양이 ''코코''', '모델 뺨치는 포즈를 보여준 코코의 인생샷들을 모았습니다. 푸른 눈이 매력적인 코코의 오후 일상.', '코코는 카메라 셔터 소리에 귀를 쫑긋거리며 우아한 자태를 뽐냈습니다. 특히 햇빛 아래 비치는 파란 눈동자가 압권이었습니다.', 'photo', 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=800', true),
('노령묘 ''먼지''의 건강 검진 동행기', '15살 먼지의 병원 방문을 도와주었습니다. 노령묘 이동 시 주의사항과 스트레스 최소화 노하우 공유.', '나이가 많은 먼지는 병원 이동 시 스트레스 예방을 위해 담요로 켄넬 전체를 덮어 시각 자극을 최소화하였고, 무사히 검진을 완료했습니다.', 'log', 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&q=80&w=800', false),
('여름철 털갈이 시즌, 효율적인 빗질법', '죽은 털을 확실하게 제거하고 피부병을 예방하는 전문가의 빗질 기술을 영상과 함께 확인하세요.', '털갈이 시즌에는 실리콘 브러시와 촘촘한 참빗을 교차 사용해야 피부 속 죽은 모근까지 깨끗하게 제거되어 피부 가려움증을 예방할 수 있습니다.', 'tip', 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=800', true),
('장난꾸러기 ''레오''의 사냥 놀이 현장', '활동량이 어마어마한 레오를 위한 맞춤형 사냥 놀이! 30분 만에 기진맥진해서 잠든 레오의 모습.', '체력이 넘치는 레오를 위해 날아다니는 카본 깃털 장난감을 사용했습니다. 공중제비를 돌며 사냥에 성공한 레오는 골골송을 부르며 꿀잠에 빠졌습니다.', 'photo', 'https://images.unsplash.com/photo-1472491235688-bdc81a63246e?auto=format&fit=crop&q=80&w=800', false);
