-- ====================================================================
-- 🐾 Yoongyopoomae (윤교품애) - 통합 Supabase DB 스키마 & RLS 정책
-- ====================================================================

-- 1. 기존 테이블 및 트리거 정리 (의존성 순서대로 삭제하여 충돌 방지)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.post_images CASCADE;
DROP TABLE IF EXISTS public.posts CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 2. Profiles 테이블 생성 (Supabase Auth.users와 1:1 매핑)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT DEFAULT 'member' CHECK (role IN ('member', 'vip', 'sitter', 'admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Posts 테이블 생성 (블로그 포스트: 돌봄일지, 전문가 팁, 사진첩)
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL DEFAULT auth.uid(), -- 작성자 계정 연동 (선택사항, RLS용)
    title TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('log', 'photo', 'tip')),
    image_url TEXT,
    is_restricted BOOLEAN DEFAULT FALSE NOT NULL, -- 회원 전용 포스트 여부
    author_name TEXT DEFAULT '전윤교 펫시터' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Post Images 테이블 생성 (이미지 업로더 연동용)
CREATE TABLE public.post_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4.5 Care Journals 테이블 생성 (돌봄 일지 관리용)
CREATE TABLE public.care_journals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT UNIQUE NOT NULL,
    photos TEXT[] DEFAULT '{}'::TEXT[],
    keywords TEXT[] DEFAULT '{}'::TEXT[],
    additional_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ====================================================================
-- 5. 자동 회원 가입 연동 트리거 (Auth.users -> Public.profiles)
-- ====================================================================
-- 사용자가 회원가입을 완료하면, auth.users 테이블의 메타데이터를 사용하여
-- public.profiles 테이블에 자동으로 사용자 정보를 연동하여 프로필 카드를 생성합니다.
-- 추가적으로, sitter@yenu.com 이메일로 가입하는 회원은 자동으로 'admin' 역할을 부여받습니다.

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, username, full_name, role)
    VALUES (
        new.id,
        new.email,
        COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'full_name', '새로운 회원'),
        CASE 
            WHEN new.email = 'sitter@yenu.com' THEN 'admin'
            WHEN new.email = 'petsitter@yenu.com' THEN 'sitter'
            ELSE 'member'
        END
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 트리거 바인딩
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ====================================================================
-- 6. RLS (Row Level Security) 행 보안 제어 설정
-- ====================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.care_journals ENABLE ROW LEVEL SECURITY;

-- 6.1 Profiles 테이블 RLS 정책
-- 누구나 다른 회원의 이름/프로필을 볼 수 있도록 SELECT 허용 (작성자 표기용)
CREATE POLICY "전체 프로필 조회 허용" 
ON public.profiles FOR SELECT 
USING (true);

-- 자기 자신의 프로필 데이터만 수정 가능
CREATE POLICY "본인 프로필만 수정 허용" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

-- 6.2 Posts 테이블 RLS 정책
-- 1) 일반 공개 게시물 (is_restricted = false)은 비로그인 유저를 포함하여 누구나 조회 가능
CREATE POLICY "공개 포스트 누구나 조회 가능" 
ON public.posts FOR SELECT 
USING (is_restricted = FALSE);

-- 2) 회원 전용 게시물 (is_restricted = true)은 로그인한 회원(member, vip, admin) 등급을 가진 유저만 조회 가능
CREATE POLICY "회원 전용 포스트 인증 회원 조회 가능" 
ON public.posts FOR SELECT 
USING (
    auth.uid() IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() 
          AND profiles.role IN ('member', 'vip', 'sitter', 'admin')
    )
);

-- 3) 포스트 생성은 로그인한 회원만 허용
CREATE POLICY "인증 회원 포스트 생성 허용" 
ON public.posts FOR INSERT 
WITH CHECK (auth.uid() IS NOT NULL);

-- 4) 포스트 수정 및 삭제는 글 작성자 본인 또는 관리자(admin) 등급만 실행 가능
CREATE POLICY "작성자 또는 어드민만 수정 및 삭제 허용" 
ON public.posts FOR ALL 
USING (
    auth.uid() = user_id 
    OR EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
);

-- 6.3 Post Images 테이블 RLS 정책
-- 1) 누구나 이미지 조회 가능
CREATE POLICY "공개 이미지 누구나 조회 가능" 
ON public.post_images FOR SELECT 
USING (true);

-- 2) 포스트 작성자 본인 또는 관리자(admin)만 사진을 추가하거나 삭제 가능
CREATE POLICY "작성자 또는 어드민만 이미지 관리 허용" 
ON public.post_images FOR ALL 
USING (
    auth.uid() IS NOT NULL AND (
        EXISTS (
            SELECT 1 FROM public.posts
            WHERE posts.id = post_images.post_id
              AND (posts.user_id = auth.uid() OR EXISTS (
                  SELECT 1 FROM public.profiles
                  WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
              ))
        )
    )
);

-- 6.4 Care Journals 테이블 RLS 정책
-- 1) 누구나 조회 가능 (보호자가 로그인 없이 공유 링크로 접근할 수 있어야 함)
CREATE POLICY "돌봄일지 누구나 조회 가능" 
ON public.care_journals FOR SELECT 
USING (true);

-- 2) 펫시터 또는 관리자(admin)만 돌봄일지 등록/수정/삭제 허용
CREATE POLICY "펫시터 및 어드민만 돌봄일지 권한 허용" 
ON public.care_journals FOR ALL 
USING (
    auth.uid() IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE profiles.id = auth.uid() AND profiles.role IN ('sitter', 'admin')
    )
);

-- ====================================================================
-- 7. Storage (버킷 생성 및 권한 설정)
-- ====================================================================
-- 'post-images' Storage 버킷 등록
INSERT INTO storage.buckets (id, name, public) 
VALUES ('post-images', 'post-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage 버킷 RLS 보안 정책 설정 (기존 정책 존재 시 충돌 방지 위해 조건 적용)
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'post-images');

DROP POLICY IF EXISTS "Authenticated Users Upload" ON storage.objects;
CREATE POLICY "Authenticated Users Upload" 
ON storage.objects FOR INSERT 
TO authenticated 
WITH CHECK (bucket_id = 'post-images');

DROP POLICY IF EXISTS "Authenticated Users Delete" ON storage.objects;
CREATE POLICY "Authenticated Users Delete" 
ON storage.objects FOR DELETE 
TO authenticated 
USING (bucket_id = 'post-images');

-- ====================================================================
-- 8. 기초 테스트 시드 데이터 (Seed Data)
-- ====================================================================
INSERT INTO public.posts (title, excerpt, content, category, image_url, is_restricted, author_name)
VALUES 
(
  '치즈냥이 ''보리''의 첫 방문 돌봄 일지', 
  '겁이 많은 보리와 친해지기 위해 조심스럽게 다가갔던 첫 날의 기록입니다. 간식 하나로 마음을 열어준 보리...', 
  '보리는 낯가림이 아주 심하고 소리에 예민한 아이였습니다. 몸을 웅크린 채 경계했으나, 1.5m 거리를 두고 낮게 앉아 눈인사를 주고 받으며 20분간 기다렸습니다. 다행히 츄르 냄새를 맡고 천천히 걸어나와 핥아 먹었으며, 감자 2개를 캐고 모래 뒤집기 정리까지 완료했습니다. 첫 만남 치고 아주 긍정적인 신호입니다.', 
  'log', 
  'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=800', 
  true,
  '전윤교 펫시터'
),
(
  '외출 시 고양이 물그릇 배치 꿀팁 💧', 
  '고양이가 물을 더 많이 마시게 하는 효율적인 배치 장소와 신선도 유지 방법 5가지를 소개합니다.', 
  '고양이는 선천적으로 흐르는 깨끗한 물을 좋아하며, 자신의 사료 옆에 있는 물은 신선하지 않다고 여기는 야생 본능이 있습니다. 따라서 밥그릇과 물그릇은 최소 1.5미터 이상 떨어트려 집안의 길목(캣타워 밑, 거실 코너 등) 곳곳에 총 3개 이상 분산 배치해 주세요. 음수량이 최소 30% 이상 확연히 증가하게 됩니다.', 
  'tip', 
  'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&q=80&w=800', 
  false,
  '전윤교 펫시터'
),
(
  '오늘의 묘델: 우아한 샴 고양이 ''코코'' 😻', 
  '모델 뺨치는 포즈를 보여준 코코의 인생샷들을 모았습니다. 푸른 눈이 매력적인 코코의 오후 일상.', 
  '카메라 렌즈를 두려워하지 않고 오히려 웅장한 포즈를 뽐내며 쳐다보는 샴 고양이 코코입니다. 햇살이 내리쬐는 창가 캣폴 위에서 반짝이는 푸른 눈망울이 정말 매혹적이었던 오후였습니다. 보호자님이 가장 아끼시는 특제 깃털 장난감으로 활기 넘치는 사냥 활동도 완료했습니다.', 
  'photo', 
  'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=800', 
  true,
  '전윤교 펫시터'
),
(
  '노령묘 ''먼지''의 건강 검진 동행기 🏥', 
  '15살 먼지의 병원 방문을 도와주었습니다. 노령묘 이동 시 주의사항과 스트레스 최소화 노하우 공유.', 
  '나이가 많은 노령묘 먼지의 정기 피검사 날이었습니다. 고양이 켄넬 내부 공간에 보호자의 냄새가 짙게 밴 수건을 깔아 안정감을 제공했고, 이동할 때 켄넬 위를 담요로 씌워 시야를 가려 이동 중 스트레스를 대폭 최소화했습니다. 수의사 소견으로 관절 보조제 증량이 필요하다고 하여 보호자 지침판에 기록했습니다.', 
  'log', 
  'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&q=80&w=800', 
  false,
  '전윤교 펫시터'
),
(
  '여름철 털갈이 시즌, 효율적인 빗질법 ✂️', 
  '죽은 털을 확실하게 제거하고 피부병을 예방하는 전문가의 빗질 기술을 확인하세요.', 
  '고양이가 죽은 털을 핥아 먹어 위 내 헤어볼이 뭉치면 장폐색으로 이어질 수 있습니다. 빗질 시에는 먼저 실리콘 재질의 부드러운 브러시로 결 방향에 맞춰 전체적인 죽은 털을 긁어 모은 후, 금속 재질의 촘촘한 참빗으로 꼬리부터 머리 방향으로 거꾸로 빗겨 잔여 모근 속 가려움을 해소해 주세요. 마지막에 젖은 타월로 마무리하는 것이 좋습니다.', 
  'tip', 
  'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=800', 
  true,
  '전윤교 펫시터'
),
(
  '장난꾸러기 ''레오''의 사냥 놀이 현장 🎾', 
  '활동량이 어마어마한 레오를 위한 맞춤형 사냥 놀이! 30분 만에 기진맥진해서 잠든 레오의 모습.', 
  '성묘 레오의 지칠 줄 모르는 사냥 욕구를 풀어주기 위해 카본 스틱 낚싯대 장난감을 사용했습니다. 마구 달아나는 사냥감의 불규칙한 회전을 재현해주니 공중제비 3바퀴를 성공하고 사냥에 성공해 웅장하게 그르렁거렸습니다. 30분 집중 놀이 후 꿀잠을 자며 휴식을 취하는 귀여운 모습입니다.', 
  'photo', 
  'https://images.unsplash.com/photo-1472491235688-bdc81a63246e?auto=format&fit=crop&q=80&w=800', 
  false,
  '전윤교 펫시터'
);
