-- ====================================================================
-- 🐾 Vibe Cat Care (전윤교의 고양이 돌봄 블로그) - 사용자 지정 데이터베이스 스키마
-- ====================================================================

-- 1. Profiles 테이블 생성 (Supabase Auth.users와 1:1 매핑)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  username TEXT UNIQUE,
  full_name TEXT,
  role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin')) -- 일반유저/관리자 구분
);

-- 2. Posts 테이블 생성
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT DEFAULT '일반',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. 돌봄일지 사진을 저장할 post_images 테이블 생성
CREATE TABLE IF NOT EXISTS public.post_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL, -- Supabase Storage의 Public URL 저장
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. RLS(행 단위 보안) 활성화
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_images ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5. RLS 정책(Policy) 설정
-- ==========================================

-- 5.1 Posts 테이블 RLS 정책
-- 전체 공개 읽기 허용
DROP POLICY IF EXISTS "Allow public read access" ON public.posts;
CREATE POLICY "Allow public read access" ON public.posts 
  FOR SELECT USING (true);

-- 인증된 사용자만 생성 가능
DROP POLICY IF EXISTS "Allow authenticated insert" ON public.posts;
CREATE POLICY "Allow authenticated insert" ON public.posts 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 작성자 본인 또는 관리자(admin)만 삭제 가능
DROP POLICY IF EXISTS "Allow delete for owners or admins" ON public.posts;
CREATE POLICY "Allow delete for owners or admins" ON public.posts
  FOR DELETE USING (
    auth.uid() = user_id 
    OR 
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
  );

-- 5.2 Profiles 테이블 RLS 정책
DROP POLICY IF EXISTS "Allow public read profiles" ON public.profiles;
CREATE POLICY "Allow public read profiles" ON public.profiles 
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow update for owners" ON public.profiles;
CREATE POLICY "Allow update for owners" ON public.profiles 
  FOR UPDATE USING (auth.uid() = id);

-- 5.3 post_images 테이블 RLS 정책
-- 누구나 사진 조회 가능
DROP POLICY IF EXISTS "Allow public read access to images" ON public.post_images;
CREATE POLICY "Allow public read access to images" ON public.post_images 
  FOR SELECT USING (true);

-- 인증된 사용자가 본인 글에 사진을 추가하는 것 허용
DROP POLICY IF EXISTS "Allow authenticated insert to images" ON public.post_images;
CREATE POLICY "Allow authenticated insert to images" ON public.post_images 
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.posts 
      WHERE posts.id = post_images.post_id AND posts.user_id = auth.uid()
    )
  );

-- 본인 글의 사진만 삭제 가능
DROP POLICY IF EXISTS "Allow delete for post owners" ON public.post_images;
CREATE POLICY "Allow delete for post owners" ON public.post_images
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.posts 
      WHERE posts.id = post_images.post_id AND posts.user_id = auth.uid()
    )
  );


-- ==========================================
-- 6. 테스트용 기초 데이터 삽입 (Seed Data)
-- ==========================================
-- [안내] 실 서비스 연동 시 아래 시드 구문을 SQL Editor에서 구동하여 즉시 데이터 카드를 생성할 수 있습니다.
/*
-- 프로필 등록 샘플
INSERT INTO public.profiles (id, username, full_name, role)
VALUES 
('11111111-1111-1111-1111-111111111111', 'sitter_jeon', '전윤교 펫시터', 'admin'),
('22222222-2222-2222-2222-222222222222', 'user_kim', '김미선 회원', 'user');

-- 포스트 작성 샘플
INSERT INTO public.posts (user_id, title, content, category)
VALUES 
('11111111-1111-1111-1111-111111111111', '치즈냥이 ''보리''의 첫 방문 돌봄 일지', '겁이 많은 보리와 친해지기 위해 조심스럽게 다가갔던 첫 날의 기록입니다. 간식 하나로 마음을 열어준 보리...', '돌봄 일지'),
('11111111-1111-1111-1111-111111111111', '외출 시 고양이 물그릇 배치 꿀팁', '고양이가 물을 더 많이 마시게 하는 효율적인 배치 장소와 신선도 유지 방법 5가지를 소개합니다.', '전문가 팁');

-- 포스트 이미지 샘플
INSERT INTO public.post_images (post_id, image_url)
VALUES
(1, 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=800'),
(2, 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&q=80&w=800');
*/
